const specifications = [
  {"key": "Details", "value": detailsList},
  {"key": "Warranty / Certifications", "value": warrantyList},
  {"key": "Dimensions", "value": dimensionsList}
];

const detailsList = [
  {"name": "Amperage (A)", "value": "40 A"},
  {"name": "Appliance Category", "value": "Range"},
  {"name": "Appliance Series", "value": "Not Applicable"},
  {"name": "Appliance Type", "value": "Electric Range"},
  {"name": "Capacity of Oven (cu. ft.)", "value": "5.0 cu ft"},
  {"name": "Capacity of Oven (cu. ft.)", "value": "5 cu ft."},
  {"name": "Cleaning Type", "value": "Manual Clean"},
  {"name": "Color of Cooktop", "value": "Black"},
  {"name": "Color/Finish", "value": "Stainless Steel"},
  {"name": "Color/Finish Family", "value": "Stainless Steel"},
  {"name": "Commercial/Residential", "value": "Residential"},
  {"name": "Control Type", "value": "Electronic"},
  {"name": "Controls Location", "value": "Back Control"},
  {"name": "Cooktop Features", "value": "Indicator Light- Heating Element On"},
  {"name": "Cooktop Surface Type", "value": "Coil"},
  {"name": "Drawer Type", "value": "Lower Storage Drawer"},
  {"name": "Element No.1 Type", "value": "Coil"},
  {"name": "Element No.1 Wattage", "value": "2400"},
  {"name": "Element No.2 Type", "value": "Coil"},
  {"name": "Element No.2 Wattage", "value": "1250"},
  {"name": "Element No.3 Type", "value": "Coil"},
  {"name": "Element No.3 Wattage", "value": "2400"},
  {"name": "Element No.4 Type", "value": "Coil"},
  {"name": "Element No.4 Wattage", "value": "1250"},
  {"name": "Fuel Type", "value": "Electric"},
  {"name": "Hardware Color/Finish", "value": "Black"},
  {"name": "Hardware Color/Finish Family", "value": "Black"},
  {"name": "Included", "value": "No Additional Items Included"},
  {"name": "Number of Elements", "value": "4 element"},
  {"name": "Number of Oven Racks", "value": "2"},
  {"name": "Number of Rack Positions", "value": "6"},
  {"name": "Oven Cleaning Options", "value": "Manual Clean"},
  {"name": "Oven Cooking Process", "value": "Standard"},
  {"name": "Oven Features", "value": "Standard Features Only"},
  {"name": "Product Weight (lb.)", "value": "142 lb"},
  {"name": "Range Installation Type", "value": "Freestanding"},
  {"name": "Returnable", "value": "Non-Returnable"},
  {"name": "Voltage (V)", "value": "240 V"},
];

const warrantyList = [
  {"name": "Certifications and Listings", "value": "UL Listed"},
  {"name": "Manufacturer Warranty", "value": "Limited 1-year entire appliance"},
];

const dimensionsList = [
  {"name": "Depth With Door(s) Open 90 Degrees (in.)", "value": "46.25 in"},
  {"name": "Element No.1 Size (in.)", "value": "8 in"},
  {"name": "Element No.2 Size (in.)", "value": "6 in"},
  {"name": "Element No.3 Size (in.)", "value": "8 in"},
  {"name": "Element No.4 Size (in.)", "value": "6 in"},
  {"name": "Oven Interior Depth (in)", "value": "18.5"},
  {"name": "Oven Interior Height (in)", "value": "19"},
  {"name": "Oven Interior Width (in)", "value": "23.75"},
  {"name": "Product Depth (in.)", "value": "28.75 in"},
  {"name": "Product Height (in.)", "value": "47 in"},
  {"name": "Product Width (in.)", "value": "30 in"},
  {"name": "Range Size (Width)", "value": "30 in."},
];
